package MCalculadora;


/**
* MCalculadora/ICalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* miércoles 1 de marzo de 2023 23H05' CET
*/

public interface ICalculadoraOperations 
{
  int sumar (MCalculadora.Operadores Ops);
  int restar (MCalculadora.Operadores Ops);
  int multiplicar (MCalculadora.Operadores Ops);
  int dividir (MCalculadora.Operadores Ops);
  double MPH_KMH (MCalculadora.Operadores Ops);
  double IVA (MCalculadora.Operadores Ops);
  double Raiz (MCalculadora.Operadores Ops);
} // interface ICalculadoraOperations
