package MCalculadora;


/**
* MCalculadora/ICalculadora.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* Tuesday, April 30, 2019 10:18:32 AM CDT
*/

public interface ICalculadora extends ICalculadoraOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICalculadora
