package MCalculadora;


/**
* MCalculadora/ICalculadora.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* miércoles 1 de marzo de 2023 23H05' CET
*/

public interface ICalculadora extends ICalculadoraOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICalculadora
