package MCalculadora;


/**
* MCalculadora/ICalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* Tuesday, April 30, 2019 10:18:32 AM CDT
*/

public interface ICalculadoraOperations 
{
  int sumar (MCalculadora.Operadores Ops);
  int restar (MCalculadora.Operadores Ops);
  int multiplicar (MCalculadora.Operadores Ops);
  int dividir (MCalculadora.Operadores Ops);
} // interface ICalculadoraOperations
